<script>
	import { onMount } from 'svelte';
	import { dataStore, fetchData, addData } from '$lib/store/dataStore';
	onMount(async () => {
		await fetchData('images');
	});

	let imageUrl = $state();
	let prompt = $state();
	let loading = $state();
	let error = $state();
	let data = $state(dataStore);

	async function generate() {
		if (!prompt.trim()) {
			error = 'Type in a prompt.';
			return;
		}

		loading = true;
		let refinedPrompt = `Design a cheerful and vibrant cereal box showing ${prompt}. Show the entire one box facing foward on a table with bright lighting.`;

		try {
			const response = await fetch('/api/image', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({ refinedPrompt })
			});

			const imgResult = await response.json();

			if (!response.ok) {
				throw new Error(data.error || 'Failed to generate image.');
			}
			imageUrl = imgResult.secure_url;
			let newData = { imageUrl: imageUrl, prompt: prompt };
			await addData(newData);
		} catch (err) {
			console.error(err);
			error = err.message;
		} finally {
			loading = false;
		}
	}
</script>

<div class="main">
	<h1 id="title">Surreal Cereal</h1>
	<textarea bind:value={prompt} placeholder="Enter your cereal box description here..." rows="4"
	></textarea>
	<button onclick={generate}>{loading ? 'Generating...' : 'Generate'}</button>
</div>

{#if error !== undefined}
	<p>{error}</p>
{/if}

{#if imageUrl !== undefined}
	<img src={imageUrl} alt="Generated by OpenAI's DALL-E" />
{/if}

{#if $data.length > 0}
		{#each $data as item}
			<img alt="Generated Cereal Box Cover" src={item.imageUrl}/>
		{/each}

{:else}
	<p>Loading...</p>
{/if}
